version: "3.8"

services:
  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    ports:
      - "9092:9092"
    environment:
      BITNAMI_DEBUG: true
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CLUSTER_ID: cc9f5eed9012
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9091
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9090,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env 
  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "9000:9000"
    env_file:
      - ./backend/api-gateway/.env
    environment:
      SPRING_EUREKA_CLIENT_SERVICE-URL: ${EUREKA_URL}
    depends_on:
      - eureka-server
  eureka-server:
    build: ./backend/eureka-server
    ports:
      - "8761:8761"
    env_file:
      - ./backend/eureka-server/.env
  user-service:
    build: ./backend/microuser
    ports:
      - "8081:8081"
    env_file:
      - ./backend/microuser/.env
    depends_on:
      - api-gateway
      - kafka
      - database
      - eureka-server
    environment:
      SPRING_JWT_SECRET: ${JWT_SECRET}
      SPRING_EUREKA_CLIENT_SERVICE-URL: ${EUREKA_URL}
      SPRING_DATASOURCE_URL:  jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  chat-service:
    build: ./backend/microchat
    ports:
      - "8082:8082"
    env_file:
      - ./backend/microchat/.env
    depends_on:
      - kafka
      - database
      - eureka-server
      - api-gateway
    environment:
      SPRING_JWT_SECRET: ${JWT_SECRET}
      SPRING_EUREKA_CLIENT_SERVICE-URL: ${EUREKA_URL}
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  auth-service:
    build: ./backend/microauth
    ports:
      - "8080:8080"
    env_file:
      - ./backend/microauth/.env
    depends_on:
      - kafka
      - database
      - eureka-server
      - api-gateway
    environment:
      SPRING_JWT_SECRET: ${JWT_SECRET}
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_EUREKA_CLIENT_SERVICE-URL: ${EUREKA_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  message-service:
    build: ./backend/micromessage
    ports:
      - "8083:8083"
    env_file:
      - ./backend/micromessage/.env
    depends_on:
      - kafka
      - database
      - eureka-server
      - api-gateway
    environment:
      SPRING_JWT_SECRET: ${JWT_SECRET}
      SPRING_EUREKA_CLIENT_SERVICE-URL: ${EUREKA_URL}
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}   
